version: 1.0.0.{build}
image: Visual Studio 2017
before_build:
 - dotnet restore
build:
 project: TinyMenu.sln
after_build:
 - dotnet pack "TinyMenu\TinyMenu.csproj"
artifacts:
 - path: 'TinyMenu.*.nupkg'
