version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
 - dotnet restore
build:
 project: TinyMenu.sln
after_build:
 - dotnet pack /p:PackageVersion=%APPVEYOR_BUILD_VERSION% "TinyMenu\TinyMenu.csproj"
artifacts:
 - path: '**\TinyMenu.*.nupkg'
