version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
 - dotnet restore
build:
 project: TinyMenu.sln
 publish_nuget: true
after_build:
 - dotnet pack "TinyMenu\TinyMenu.csproj"
artifacts:
 - path: '**\TinyMenu.*.nupkg'
deploy:
 - provider: NuGet
   api_key:
     secure: 4MBiCVgduJ+5E6lzASSOmhHUb+XlTEfU56vsO1iC3pp/bJkkdcgii9RARoTzOKax
   artifact: /TinyMenu.*\.nupkg/
